Controllers/CrudUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoAnalisis.Datos;
using ProyectoAnalisis.Models;
using ProyectoAnalisis.Recursos;

namespace ProyectoAnalisis.Controllers
{
    public class CrudUsuariosController : Controller
    {
        private readonly BaseDeDatosUsuario _context;

        public CrudUsuariosController(BaseDeDatosUsuario context)
        {
            _context = context;
        }



        // GET: CrudUsuarios
        public async Task<IActionResult> Index()
        {
              return _context.Usuario != null ? 
                          View(await _context.Usuario.ToListAsync()) :
                          Problem("Entity set 'BaseDeDatosUsuario.Usuario'  is null.");
        }

        // GET: CrudUsuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: CrudUsuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CrudUsuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Rol,Contraseña,Direccion,CorreoElectronico")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                //se usa la clase encriptar clave para guardarla en la Bd
                usuario.Contraseña = Utilidades.EncriptarClave(usuario.Contraseña);

                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: CrudUsuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: CrudUsuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Usuario usuario)
        {
            Console.WriteLine($"Entrando al método Edit con ID: {id}, Usuario ID: {usuario.Id}");

            // Elimina el error de validación para el campo Contraseña
            // cuando no se proporciona una nueva contraseña durante la edición del usuario, no hay problema
            ModelState.Remove("Contraseña");

            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Console.WriteLine("ModelState es válido");
                try
                {
                    // Obtener el usuario original de la base de datos
                    var usuarioOriginal = await _context.Usuario.FindAsync(id);

                    if (usuarioOriginal == null)
                    {
                        return NotFound();
                    }

                    // Asignar la contraseña original al usuario que se está editando
                    usuario.Contraseña = usuarioOriginal.Contraseña;

                    // Modificar las propiedades del usuario original con los valores del usuario que se está editando
                    _context.Entry(usuarioOriginal).CurrentValues.SetValues(usuario);

                    // Guardar los cambios en la base de datos
                    await _context.SaveChangesAsync();

                    TempData["MensajeExito"] = "Usuario actualizado correctamente";
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    Console.WriteLine($"Error al actualizar: {ex.Message}");
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            else
            {
                Console.WriteLine("ModelState no es válido:");
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine($"- {error.ErrorMessage}");
                }
            }

            TempData["MensajeError"] = "Hubo un problema al actualizar el usuario. Verifique los datos e intente nuevamente.";

            return View(usuario);
        }


        // GET: CrudUsuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
           
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }
      
            return View(usuario);
        }
        // POST: CrudUsuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }

            // Verificar si existen notas asociadas al usuario
            var notasAsociadas = await _context.Notas.Where(n => n.UsuarioId == id).ToListAsync();
            if (notasAsociadas.Any())
            {
                // Eliminar las notas asociadas al usuario
                _context.Notas.RemoveRange(notasAsociadas);
      
            }
        

            // Eliminar el usuario
            _context.Usuario.Remove(usuario);

            // Guardar los cambios en la base de datos
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        private bool UsuarioExists(int id)
        {
          return (_context.Usuario?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var user = Context.User;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoAnalisis</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Acme&family=Lora:wght@700&family=Montserrat:wght@900&family=Poppins:wght@800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap">
    <link rel="stylesheet" href="/css/EstiloMisDatos.css">
    <style>
      .banner-image {
            background-image: url('@Url.Content("~/Img/Paisaje.jpg")');
            background-size: cover;
            opacity: 0.8;
        }

     
        .navbar-dark .navbar-nav .nav-link {
            color:black;
            font-weight: bold;
            background-color: transparent;
        }

        #navbar-brand {
            color: black; /* Cambia el color del texto a negro */
            font-weight: bold;
            font-family: 'Poppins', sans-serif;
            font-size: 35px;
            margin-left: 70px;
            font-weight: 900;


        }

        .navbar-nav .nav-link {
            font-size: 20px; /* Cambia el tamaño del texto a 20px */
            background-color: transparent;
        }

        .navbar {
            margin-left: -145px !important;
            background-color: transparent;
        }

    
        .dropdown-item {
            color: black;
            font-weight: bold;
        }

        #dropdownMenuButton{
            background-color: transparent;
            border: none;
            color:black;
            font-weight: bold;
            font-size: 20px;
        }



            #dropdownMenuButton:hover,
            #dropdownMenuButton:active,
            #dropdownMenuButton:focus{
                background-color: #FE7800;
                box-shadow: none;
                border: none;
                color:white;
           
            }


            #dropdownMenuButton:not(:hover),
            #dropdownMenuButton:not(:focus) {
                background-color: transparent;
                border: none;
                color: black;
            }


        .dropdown-item:hover,
        .dropdown-item:focus {
            background-color: #FE7800;
            border:none;
            color:white;
        }

  

        .btn-secondary {
            background-color: transparent;
            color: black;
            font-weight: bold;
            border:none;
            font-size: 20px;
        }


        .btn-secondary:hover,
        .btn-secondary:focus {
            background-color: #FE7800;
        
        }

   

    </style>
</head>
<body>
    <!-- Navbar  -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark p-md-3">
        <div class="container">
            
            <span id="navbar-brand"> <img src="~/Img/fox (1).png" alt="Icono de zorro" style="width: 80px;">EnglishFox</span>


            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="mx-auto"></div>
                <ul class="navbar-nav  mi-lista">
                    @if (user.IsInRole("Profesor")) // Verificar si el usuario tiene el rol "Profesor" si lo tiene muestra esta vista
                    {
                        <li class="nav-item dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Maestro
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="background-color: transparent;">
                                <a class="dropdown-item" asp-area="" asp-controller="CrudUsuarios" asp-action="Index">Usuario</a>
                                <!-- En tu vista donde tienes el enlace -->
                                <a class="dropdown-item" asp-area="" asp-controller="ConsultarNotas" asp-action="Index">Consultar Notas</a>
                            </div>
                        </li>
                    }

                    <li class="nav-item dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Contenido
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="background-color: transparent;">
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Contenido">Contenido</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home"  asp-action="Volver">Volver</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Gramatica">Gramatica Presente simple </a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Vocabulario" >Vocabulario </a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Videos">Videos Informativos</a>

                        </div>
                    </li>

                        <li class="nav-item dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Evaluativo
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="background-color: transparent;">

                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Juego">Juego</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Repasos">Repasos</a>
                            <a class="dropdown-item" asp-controller="HistorialPuntuacion" asp-action="Index">Ver Historial de Puntuaciones</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home"  asp-action="Volver">Volver</a>
                         
                        </div>
                    </li>
                    <li class="nav-item">
                        <form method="post" asp-area="" asp-controller="Home" asp-action="CerrarSesion">
                            <button class="btn btn-secondary" type="submit"  aria-haspopup="true" aria-expanded="false">
                                Cerrar Sesión
                            </button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <form method="post" asp-controller="Home" asp-action="MisDatos">

                            <button type="submit" class="glowing-icon-btn">
                                <img src="~/Img/UsuarioFinal.png" alt="Mis datos" width="40" height="40" class="glowing-icon">
                            </button>
                        </form>
                    </li>

                </ul>
            </div>

        </div>
    </nav>

    <!-- Banner Image  -->
    <div class="banner-image w-100 vh-100 d-flex justify-content-center align-items-center">
        <div class="content text-center">
            <h1 class="text-dark">  @RenderBody()</h1>
        </div>
    </div>



</body>

</html>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>

<!-- Popper.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

<!-- Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>